language: python

python: "2.7" 

# To access the packages inside the virtualenv
# See https://docs.travis-ci.com/user/languages/python/
virtualenv:
  system_site_packages: true

sudo: required

env:
  - DUMMY=true

git:
  depth: 1
    

before_install:
  - sudo apt-get update -qq


install:
  # Install Ansible.
  - pip install ansible
  # Add ansible.cfg to pick up roles path.
  #- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"          

before_script:
#  - 

script:
 - ./operate check test-httpd-playbook.yml 
 - ./operate test test-httpd-playbook.yml 
 - > 
   cat /tmp/index.html
   | grep 'It works!' 
   && (echo 'Httpd UP!' && exit 0)
   || (echo 'Httpd DOWN!' && exit 1)
 - ./operate test shutdown-playbook.yml
