# ansible-playbook
---
- include: shutdown-playbook.yml

- hosts: 
  - localhost
  gather_facts: yes
  vars:
  roles:
    - preconfig-sys
    - common
    - virtualbox
    - docker
    - kubernetes
    - minikube
    - httpd
