- name: Copy the yml definition files to /tmp
  copy:
    src: "{{ item }}"
    dest: /tmp
    mode: "u=rw,g=r,o=r"
  with_fileglob:
    - files/*.yml

- name: Kuberctrl create Deployment + Service + Horizontal Pod AutoScaler
  command: kubectl create -f /tmp/definition.yml

- name: (Testing only) curl http://localhost/index.html from Httpd
  shell: curl -Lo /tmp/index.html `minikube service httpd --url`  
