- name: Download minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/v0.21.0/minikube-linux-amd64 
    dest: /usr/local/bin/minikube
    mode: 0665
    checksum: sha256:c5dc6e8d85f96d4bfba321bdca93b2a828a714162653a55a9b3a6d527f517e82
  become: yes

