- name: Download minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/v0.24.1/minikube-linux-amd64 
    dest: /usr/local/bin/minikube
    mode: 0755
    checksum: sha256:1261de09386fd1f4ee7a4645958757c2c9e69f419a2a4ca8aff475017a7e036e
  become: yes

- name: Start minikube cluster
  command: minikube start --vm-driver=none --kubernetes-version=v1.8.0
  environment:
    - CHANGE_MINIKUBE_NONE_USER: true

- name: Fix the kubectl context, as it's often stale.
  command: minikube update-context

- name: (Workaround) To wait SSL service (:8443) to be ready
  pause:
    seconds: 10
  #  when: is_testing is defined

- name: Wait until minikube is up and ready - 2 min timeout
  shell: |
    for i in {1..60}; do # 60 * 2 = 2 min
       kubectl get nodes
       kubectl get nodes | grep -q 'NotReady'
       if [ $? -eq 0 ]; then
          echo 'NotReady'
          continue
       else
          echo 'Ready' 
          break
       fi
       sleep 1
    done
  args:
    executable: /bin/bash  
  #  when: is_testing is not defined


- name: Start collecting metrics
  command: minikube addons enable heapster

- name: Start up dashboard service and display in browser
  command: minikube dashboard  
  when: is_testing is not defined 

- name: Open up Grafana service and display in browser
  command: minikube addons open heapster
  when: is_testing is not defined 

